### ISSUE TITLE
Can not replace the default folder "highlight"

### ISSUE THREAD

**Issue by gzbluemix** [jiangnanandi/Obsidian-highlighter#1]
你好！这个插件很好！谢谢你的工作！但在用
“导出到 Obsidian” 时 路径中总是有“highlight“ 例如，如果路径是 ”inbox“，插件会在Obsidian中生成“highlight/inbox", 而不是“inbox”。能否去掉这个缺省“highlight”？谢谢！

**Comment by david-crafts** [comment]
好的，我在下一版中争取修复

**Comment by MiracleXYZ** [comment]
Same issue here

**Comment by david-crafts** [comment]
更新 1.1.2 版本，已经解决问题，支持自定义目录
