### ISSUE TITLE
请问 插件支持 Safari 的阅读模式吗？

### ISSUE THREAD

**Issue by Lunar-W** [jiangnanandi/Obsidian-highlighter#11]
如题。很喜欢 Safari 的阅读模式，所以从 Chrome 换到 Safari，所以想问一下插件是否支持阅读模式。

**Comment by david-crafts** [comment]
你好，不支持阅读模式。
后期有时间可以考虑类似「简悦」那样的阅读模式摘录。目前精力有限。

**Comment by david-crafts** [comment]
problem solved
