### ISSUE TITLE
请问父标题样式使用的是什么语言?

### ISSUE THREAD

**Issue by Xiy1** [jiangnanandi/Obsidian-highlighter#12]
你好, 我想在副标题里面自动填写一些信息, 例如: 日期, 时间. 我应该去哪里了解呢?

**Comment by david-crafts** [comment]
![CleanShot 2022-05-14 at 11 38 17@2x](https://user-images.githubusercontent.com/7147277/168409383-84d0de2f-4ba9-4bf3-bd10-cd7914e70e8e.png)
可以通过图中示例查看，并掌握语法。
