### ISSUE TITLE
自动高亮不能使用

### ISSUE THREAD

**Issue by CMakey** [jiangnanandi/Obsidian-highlighter#15]
在打开插件的情况且打开自动高亮，在文章中选中文字后没有标亮显示。

已经排除掉了个人认为可能导致出现bug的点：
1. popclip
2. link text selector

**Comment by david-crafts** [comment]
你好，请检查开启「自动高亮」后是否点击了「保存按钮」

![CleanShot 2022-09-18 at 12 31 02@2x](https://user-images.githubusercontent.com/7147277/190885830-5af1b584-55cb-4f89-8a20-dc7a4fe9cef6.png)

**Comment by CMakey** [comment]
emm您好，是确认点击了的，但是有极个别的网页才有问题，需要手动command+x才可以。

**Comment by david-crafts** [comment]
@CMakey 暂时关闭这个 issues ，如果还有问题请在此打开。
