### ISSUE TITLE
CANNOT OPEN

### ISSUE THREAD

**Issue by emoowang** [jiangnanandi/Obsidian-highlighter#16]
I CANNOT OPEN MY OBSIDIAN_HIGHLIGHTER. THE WINDOW ON THE RIGHT BOTTOM OF THE CURRENT PAGE CANNOT JUMP OUT EVEN AFTER MY GIVING COMMAND OF CMD+X VIA MACAIR

**Comment by david-crafts** [comment]
You can try to activate Obsidian-highlighter by clicking on the icon in the status bar of your browser, refer to the following image.


![CleanShot-2022-10-31132905@2x](https://user-images.githubusercontent.com/7147277/198937927-041a4f5f-83d1-402e-ba06-6105d4c80ce7.png)

**Comment by david-crafts** [comment]
@emoowang Temporarily assume that you no longer have this problem, if this problem still occurs, please open issues
