### ISSUE TITLE
请增加换行模式：每段高亮后增加一个换行

### ISSUE THREAD

**Issue by gogobat-2022-12** [jiangnanandi/Obsidian-highlighter#18]
如果bullets设置为：>[!quote] 
那么高亮文本为：
```
>[!quote] 与此同时，在普遍的通胀和央行货币政策收紧的背景下，全球富豪的财富也在全面下滑。
>[!quote] 不过，对亿万富豪阶层来说，今年并不全是坏消息。
```
obsidian不能识别这种格式，但是每段后面多一个换行，ob就可以很漂亮的显示高亮，并且可以直接写标注。

我感觉可以给highliter增加一种标注的使用场景

**Comment by david-crafts** [comment]
好的，争取近期增加 Feature

**Comment by david-crafts** [comment]
@gogobat-2022-12 

hi，不好意思，我已在最新版本增加了此 Feature，如果需要换行，在设置中开启如下设置即可。

![CleanShot-2023-02-08141225@2x](https://user-images.githubusercontent.com/7147277/217449506-779acb81-6963-4a21-815b-cc4fc46b1e28.png)

**Comment by david-crafts** [comment]
问题已解决
