### ISSUE TITLE
无法导出

### ISSUE THREAD

**Issue by addonico** [jiangnanandi/Obsidian-highlighter#2]
>无法导出到obsidian，库名改成自己的了，路径用的highlight/

**Comment by david-crafts** [comment]
辛苦提供具体错误，包括你的库名截图，插件中的配置截图

**Comment by Arthur-Null** [comment]
同样的问题，导出时候会打开obsidian，但没有反应
<img width="402" alt="CleanShot 2022-04-19 at 13 48 14@2x" src="https://user-images.githubusercontent.com/24970454/163928502-dc6563e7-4983-4c3f-beac-2b22cbf0572e.png">
<img width="790" alt="CleanShot 2022-04-19 at 13 49 03@2x" src="https://user-images.githubusercontent.com/24970454/163928558-766e72e4-3550-4dc6-8654-c150ed909759.png">

**Comment by david-crafts** [comment]
> 同样的问题，导出时候会打开obsidian，但没有反应
> <img alt="CleanShot 2022-04-19 at 13 48 14@2x" width="402" src="https://user-images.githubusercontent.com/24970454/163928502-dc6563e7-4983-4c3f-beac-2b22cbf0572e.png">
> <img alt="CleanShot 2022-04-19 at 13 49 03@2x" width="790" src="https://user-images.githubusercontent.com/24970454/163928558-766e72e4-3550-4dc6-8654-c150ed909759.png">

帮忙确认一下：
1. 尝试去掉 Obsidian 两边的空格（如果有的话）
2. 将 `/pages` 改成 `pages`，如果是这个的话，我会在后续版本兼容

**Comment by addonico** [comment]
将&nbsp;/pages&nbsp;改成&nbsp;pages之后可以导出了，谢谢！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: dawei ***@***.***&gt;
发送时间: 2022年4月19日 17:20
收件人: jiangnanandi/Obsidian-highlighter ***@***.***&gt;
抄送: addonico ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [jiangnanandi/Obsidian-highlighter] 无法导出 (Issue #2)





  
同样的问题，导出时候会打开obsidian，但没有反应
 
 
  
帮忙确认一下：
  
尝试去掉 Obsidian 两边的空格（如果有的话） 

将 /pages 改成 pages，如果是这个的话，我会在后续版本兼容

**Comment by Arthur-Null** [comment]
change from /pages to pages solves my problem.

**Comment by david-crafts** [comment]
问题已经解决，如果导出的 Path 中第一个字符是 '/' 怎会被替换。因为 Obsidian 的规则不允许 Path 中第一个字符是 '/'，建议不要加 '/'
