### ISSUE TITLE
All bullets are indented inherently

### ISSUE THREAD

**Issue by MiracleXYZ** [jiangnanandi/Obsidian-highlighter#3]
当打开「Indent」选项的时候，导出的结果全部是缩进过4个空格的，在预览的时候无法正常显示，而是显示为代码块。

希望在以后的版本中能够设置把这个默认的缩进去掉。

<img width="589" alt="preview" src="https://user-images.githubusercontent.com/30370926/162162772-a3302028-d12c-4735-89be-cfc50940badb.png">

<img width="589" alt="live preview" src="https://user-images.githubusercontent.com/30370926/162162872-fe0a4d79-9b40-4848-a9d7-a88b29a60e84.png">

**Comment by david-crafts** [comment]
反馈已收到，这是已知问题，后续如果修复会更新新版本的 what's new

**Comment by david-crafts** [comment]
问题已经在 v1.1.3 版本更新，感谢建议。
