### ISSUE TITLE
扩展从AppStore下载安装完后提示“清单content_scripts部分的'js'和'css'数组丢失或空白。”

### ISSUE THREAD

**Issue by luoyich** [jiangnanandi/Obsidian-highlighter#6]
macOS版本12.3.1
Safari版本15.4
安装完后，Safari扩展中显示““obsidian-highlighter Extension”出错：
清单content_scripts部分的'js'和'css'数组丢失或空白。”

**Comment by david-crafts** [comment]
感谢反馈，这个没有问题，不影响功能使用

**Comment by david-crafts** [comment]
问题已经在 v1.1.3 版本更新
